[package]
name = "factory_token"
version = "0.1.0"
cairo-version = "2.3.1"


# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true
allowed-libfuncs-list.name = "experimental"

[dependencies]
starknet = "^2.3.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }

[tool.snforge]
# exit_first = true
